import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { ArrowDownRight, ArrowRight, Atom, CalendarDays, Clock3, FlaskConical, HeartPulse, Lightbulb, Mail, MapPin, Menu, Moon, Play, Search, Send, Sun, Users, X } from 'lucide-react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import NotFound from '@/pages/not-found';
import { Route, Switch, Link, useLocation, Router as WouterRouter } from 'wouter';

const queryClient = new QueryClient();
type Status = 'upcoming' | 'past';
type EventItem = { id: string; day: string; month: string; type: 'Conference' | 'Webinar'; title: string; location: string; date: Status; speaker?: string };

const tracks = [
  { id: '01', title: 'Life sciences', copy: 'From molecular frontiers to translational care.', icon: HeartPulse },
  { id: '02', title: 'Engineering', copy: 'Systems, materials, energy, and the built world.', icon: Atom },
  { id: '03', title: 'Technology', copy: 'The tools changing how knowledge moves.', icon: FlaskConical },
  { id: '04', title: 'Medical practice', copy: 'Clinical thinking for a changing patient.', icon: Users },
  { id: '05', title: 'Academic futures', copy: 'Ideas, institutions, and the next generation.', icon: Lightbulb },
];
const events: EventItem[] = [
  { id: 'med-27', day: '12–14', month: 'MAR 27', type: 'Conference', title: 'International Conference on Medical, Life & Health Sciences', location: 'Boston, Massachusetts · Hybrid', date: 'upcoming' },
  { id: 'ai-27', day: '08–09', month: 'MAY 27', type: 'Conference', title: 'Applied Intelligence & Emerging Technologies Forum', location: 'Singapore · In person', date: 'upcoming' },
  { id: 'web-26', day: '22', month: 'OCT 26', type: 'Webinar', title: 'Precision systems: turning data into better decisions', location: 'Online · 14:00 UTC', date: 'upcoming', speaker: 'Dr. Amina Rao' },
  { id: 'climate-26', day: '04', month: 'DEC 26', type: 'Webinar', title: 'Engineering resilient cities under pressure', location: 'Online · 16:00 UTC', date: 'upcoming', speaker: 'Prof. Daniel Okafor' },
  { id: 'past-25', day: '18–20', month: 'NOV 25', type: 'Conference', title: 'Global Forum on Research Translation', location: 'Copenhagen · Hybrid', date: 'past' },
  { id: 'past-web', day: '07', month: 'JUN 25', type: 'Webinar', title: 'The evidence gap: building trust in public health', location: 'Online · 13:00 UTC', date: 'past', speaker: 'Dr. Leila Morgan' },
];
const galleryItems = ['A room for exchange', 'The work between sessions', 'Questions in the margins', 'Proof, shared openly', 'Notes become networks', 'One global conversation'];
const insights = [
  { label: 'FIELD NOTE · 08 MIN', title: 'What happens when disciplines stop working in parallel?', copy: 'A working brief on shared language, better questions, and the collaborations waiting in the middle.' },
  { label: 'PROCEEDINGS', title: 'The evidence is in the exchange.', copy: 'Selected findings from our latest rooms.' },
  { label: 'JOURNAL', title: 'Signals worth following.', copy: 'A new editorial surface is taking shape.' },
];

function useTheme() {
  const [theme, setTheme] = useState<'light' | 'dark'>(() => localStorage.getItem('stream-theme') === 'dark' ? 'dark' : window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
  useEffect(() => { document.documentElement.classList.toggle('dark', theme === 'dark'); localStorage.setItem('stream-theme', theme); }, [theme]);
  return { theme, toggle: () => setTheme((t) => t === 'dark' ? 'light' : 'dark') };
}
function useReveal() {
  useEffect(() => { const nodes = [...document.querySelectorAll<HTMLElement>('.reveal')]; const observer = new IntersectionObserver((entries) => entries.forEach((e) => { if (e.isIntersecting) { e.target.classList.add('visible'); observer.unobserve(e.target); } }), { threshold: .1 }); nodes.forEach((n) => observer.observe(n)); return () => observer.disconnect(); }, []);
}

const nav = [['Home', '/'], ['About', '/about'], ['Gallery', '/gallery'], ['Blog', '/blog'], ['Conferences', '/conferences'], ['Webinars', '/webinars'], ['Contact', '/contact']];
function Header({ theme, toggleTheme }: { theme: 'light' | 'dark'; toggleTheme: () => void }) {
  const [drawer, setDrawer] = useState(false); const [location] = useLocation();
  return <><header className="site-header"><div className="header-inner">
    <Link href="/" className="brand" onClick={() => setDrawer(false)}><span className="brand-mark">S</span><span><span className="brand-word">StreamConferences</span><span className="brand-sub">An event by Stream Conferences</span></span></Link>
    <nav className="desktop-nav" aria-label="Main navigation">{nav.map(([label, href]) => <Link key={href} href={href} className={`nav-link ${location === href ? 'active' : ''}`}>{label}</Link>)}</nav>
    <div className="header-actions"><button className="icon-button" onClick={toggleTheme} aria-label="Toggle theme">{theme === 'dark' ? <Sun size={16} /> : <Moon size={16} />}</button><Link href="/contact" className="cta-button">Register now <ArrowRight size={14} /></Link><button className="icon-button mobile-trigger" onClick={() => setDrawer(true)} aria-label="Open menu"><Menu size={19} /></button></div>
  </div></header>
  <div className={`drawer-backdrop ${drawer ? 'open' : ''}`} onClick={() => setDrawer(false)} /><aside className={`mobile-drawer ${drawer ? 'open' : ''}`}><button className="icon-button drawer-close" onClick={() => setDrawer(false)} aria-label="Close menu"><X size={18} /></button><Link href="/" className="brand" onClick={() => setDrawer(false)}><span className="brand-mark">S</span><span><span className="brand-word">StreamConferences</span><span className="brand-sub">Global research exchange</span></span></Link><nav className="drawer-nav">{nav.map(([label, href]) => <Link href={href} key={href} onClick={() => setDrawer(false)}>{label}</Link>)}</nav><Link href="/contact" className="cta-button" onClick={() => setDrawer(false)} style={{ marginTop: 34, justifyContent: 'center' }}>Register now <ArrowRight size={14} /></Link></aside></>;
}
function Shell({ children }: { children: ReactNode }) { const { theme, toggle } = useTheme(); useReveal(); return <div className="site-shell"><Header theme={theme} toggleTheme={toggle} />{children}<Footer /><Link href="/contact" className="mobile-register">Register now <ArrowRight size={14} /></Link></div>; }
function PageIntro({ kicker, title, copy }: { kicker: string; title: string; copy: string }) { return <section className="page-intro bg-grid"><div className="section reveal"><div className="section-kicker">{kicker}</div><h1 className="page-title">{title}</h1><p className="page-copy">{copy}</p></div></section>; }
function Countdown() { const target = useMemo(() => new Date('2027-03-12T08:30:00Z').getTime(), []); const [left, setLeft] = useState(Math.max(0, target - Date.now())); useEffect(() => { const t = setInterval(() => setLeft(Math.max(0, target - Date.now())), 1000); return () => clearInterval(t); }, [target]); const units = [['days', Math.floor(left / 86400000)], ['hours', Math.floor(left / 3600000) % 24], ['minutes', Math.floor(left / 60000) % 60], ['seconds', Math.floor(left / 1000) % 60]]; return <section className="countdown-section"><div className="countdown-inner reveal"><div><div className="live-pill"><span className="live-dot" /> Next on the programme</div><h2 className="countdown-title">The next conversation starts here.</h2><p className="countdown-copy">A focused online briefing on precision systems, better decisions, and the evidence that makes both possible.</p><Link href="/webinars" className="cta-button">Explore webinars <Play size={13} fill="currentColor" /></Link></div><div className="countdown-boxes">{units.map(([label, value]) => <div className="count-box" key={label}><b>{String(value).padStart(2, '0')}</b><small>{label}</small></div>)}</div></div></section>; }
function EventList({ initial: initialStatus = 'upcoming', onlyType }: { initial?: Status; onlyType?: 'Conference' | 'Webinar' }) { const [status, setStatus] = useState<Status>(initialStatus); const [query, setQuery] = useState(''); const [type, setType] = useState<'All' | 'Conference' | 'Webinar'>(onlyType ?? 'All'); const visible = events.filter((e) => e.date === status && (!onlyType ? type === 'All' || e.type === type : e.type === onlyType) && `${e.title} ${e.location} ${e.speaker ?? ''}`.toLowerCase().includes(query.toLowerCase())); return <><div className="event-toolbar reveal"><div className="segmented">{(['upcoming', 'past'] as Status[]).map((tab) => <button className={`segment ${status === tab ? 'active' : ''}`} key={tab} onClick={() => setStatus(tab)}>{tab === 'upcoming' ? 'Upcoming' : 'Past archive'}</button>)}</div>{!onlyType && <div className="segmented">{(['All', 'Conference', 'Webinar'] as const).map((tab) => <button className={`segment ${type === tab ? 'active' : ''}`} key={tab} onClick={() => setType(tab)}>{tab}</button>)}</div>}<label className="search-box"><Search size={15} /><input type="search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder={`Search ${onlyType?.toLowerCase() ?? 'events'}`} /></label></div><div className="event-list reveal">{visible.length ? visible.map((e) => <article className="event-card" key={e.id}><div className="event-date"><b>{e.day}</b><span>{e.month}</span></div><div><div className="event-type">{e.type}</div><h3>{e.title}</h3><div className="event-meta"><MapPin size={12} style={{ verticalAlign: 'middle', marginRight: 4 }} />{e.location}{e.speaker && ` · ${e.speaker}`}</div></div><Link href="/contact" className="event-arrow" aria-label={`View ${e.title}`}><ArrowDownRight size={16} /></Link></article>) : <div className="empty-state">No events match that search.</div>}</div></>; }
function Hero() { return <><section className="hero"><div className="hero-inner"><div className="reveal"><div className="eyebrow orange">The global conference hub · SC / 27</div><h1>Where serious ideas <em>move forward.</em></h1><p className="hero-copy">Stream Conferences brings the people who discover, test, build, and deliver better futures into one serious global conversation.</p><div className="hero-actions"><Link className="cta-button" href="/conferences">Explore conferences <ArrowRight size={14} /></Link><Link className="hero-link" href="/about">Why Stream <span>→</span></Link></div></div><aside className="field-note reveal"><div className="note-top"><span>Field note / 001</span><span>◌</span></div><p className="note-quote">“Research becomes real when disciplines stop working in parallel.”</p><div className="note-bottom"><span>Stream / Global</span><span>Est. 2014</span></div></aside></div></section><section className="info-strip"><div className="info-inner"><div className="info-cell"><div className="info-label">Featured conference</div><div className="info-value">International Conference on Medical, Life &amp; Health Sciences</div></div><div className="info-cell"><div className="info-label"><CalendarDays size={12} /> Dates</div><div className="info-value">March 12—14, 2027</div></div><div className="info-cell"><div className="info-label"><MapPin size={12} /> Venue</div><div className="info-value">Boston, Massachusetts · USA</div></div></div></section></>; }
function Slider() { const [active, setActive] = useState(0); useEffect(() => { const t = setInterval(() => setActive((a) => (a + 1) % galleryItems.length), 4500); return () => clearInterval(t); }, []); return <section className="section slider-section"><div className="section-heading reveal"><div><div className="section-kicker">Inside the exchange</div><h2 className="section-title">Ideas are better in the room.</h2></div><Link href="/gallery" className="ghost-button">View gallery <ArrowRight size={14} /></Link></div><div className="slider reveal"><div className="slider-art" style={{ backgroundPosition: `${active * 20}% 50%` }}><div className="slider-caption"><span>0{active + 1} / 0{galleryItems.length}</span><h3>{galleryItems[active]}</h3></div><div className="slider-controls">{galleryItems.map((_, i) => <button key={i} className={active === i ? 'active' : ''} onClick={() => setActive(i)} aria-label={`Show slide ${i + 1}`} />)}</div></div></div></section>; }
function Home() { return <Shell><main><Hero /><section className="section"><div className="narrative reveal"><p className="narrative-statement">Not just another event. <span>A better way to gather.</span></p><div className="narrative-body"><p>Stream is an independent conference and webinar platform for the people doing the work. We build precise, generous spaces for research to meet practice — across medicine, technology, engineering, and academia.</p><p><strong>We care about the signal.</strong> Fewer filler panels, more useful questions, and programmes shaped around real problems.</p><div className="stat-row"><div className="stat"><strong>42</strong><small>Countries connected</small></div><div className="stat"><strong>18k</strong><small>Annual participants</small></div><div className="stat"><strong>11</strong><small>Years convening</small></div></div></div></div></section><section className="section-tint"><div className="section"><div className="section-heading reveal"><div><div className="section-kicker">Five directions</div><h2 className="section-title">Find your current.</h2></div><p className="section-intro">One parent brand, five ways into the conversation.</p></div><div className="tracks reveal">{tracks.map((t) => { const Icon = t.icon; return <article className="track-card" key={t.id}><div><div className="track-number">{t.id}</div><div className="track-icon"><Icon size={20} /></div></div><div><h3>{t.title}</h3><p>{t.copy}</p></div></article>; })}</div></div></section><Countdown /><section className="section"><div className="section-heading reveal"><div><div className="section-kicker">The full programme</div><h2 className="section-title">Conferences &amp; webinars.</h2></div><Link href="/conferences" className="ghost-button">See all events <ArrowRight size={14} /></Link></div><EventList /></section><Slider /><section className="section-tint"><div className="section"><div className="section-heading reveal"><div><div className="section-kicker">The editorial desk</div><h2 className="section-title">A little more to take with you.</h2></div><Link href="/blog" className="ghost-button">Read the blog <ArrowRight size={14} /></Link></div><div className="journal-grid reveal">{insights.map((i, n) => <article className={`insight-card ${n === 0 ? 'featured' : ''}`} key={i.label}><div><span className="soon">{i.label}</span><h3>{i.title}</h3><p>{i.copy}</p></div><Link href="/blog" className="read-link">{n === 0 ? 'Read the field note' : 'Coming soon'} <ArrowRight size={13} /></Link></article>)}</div></div></section><ContactBand /></main></Shell>; }
function About() { return <Shell><main><PageIntro kicker="The people behind the platform" title="About Stream Conferences." copy="Connecting minds, advancing science through precise, generous spaces for research to meet practice." /><section className="section"><div className="narrative reveal"><p className="narrative-statement">We build rooms where <span>knowledge travels.</span></p><div className="narrative-body"><p>Stream Conferences is a global architect of scientific, technical, research, engineering, academic, and medical summits. We bring rigorous scholarship and industrial execution into the same room.</p><p>Our programmes are designed to accelerate knowledge transfer, forge cross-disciplinary relationships, and turn theoretical discoveries into transformative global solutions.</p></div></div></section><section className="section-tint"><div className="section"><div className="section-heading reveal"><div><div className="section-kicker">What guides us</div><h2 className="section-title">The work behind the work.</h2></div></div><div className="tracks reveal">{['Scientific integrity', 'Action-driven innovation', 'Multidisciplinary synergy', 'Global inclusivity', 'Academic excellence'].map((title, i) => <article className="track-card" key={title}><div className="track-number">0{i + 1}</div><div><h3>{title}</h3><p>High standards, useful connections, and a clear path from discovery to impact.</p></div></article>)}</div></div></section><ContactBand /></main></Shell>; }
function Gallery() { const [selected, setSelected] = useState<string | null>(null); return <Shell><main><PageIntro kicker="Inside the exchange" title="A gallery of ideas in motion." copy="A glimpse at the people, notes, and productive friction that make a Stream gathering feel different." /><section className="section"><div className="gallery-grid reveal">{galleryItems.map((item, i) => <button className="gallery-item" key={item} onClick={() => setSelected(item)}><span className="gallery-caption">{item}<ArrowRight size={14} /></span></button>)}</div></section>{selected && <div className="lightbox" onClick={() => setSelected(null)}><div className="lightbox-card" onClick={(e) => e.stopPropagation()}><button className="icon-button lightbox-close" onClick={() => setSelected(null)} aria-label="Close"><X size={17} /></button><div className="lightbox-art"><h3>{selected}</h3></div></div></div>}</main></Shell>; }
function Blog() { return <Shell><main><PageIntro kicker="The editorial desk" title="Notes for the curious." copy="Field notes, proceedings, and useful context from the conversations we host." /><section className="section"><div className="journal-grid reveal">{insights.concat([{ label: 'FIELD NOTE · 04 MIN', title: 'A better question is a better beginning.', copy: 'How the right prompt changes the room.' }]).map((i, n) => <article className={`insight-card ${n === 0 ? 'featured' : ''}`} key={i.title}><div><span className="soon">{i.label}</span><h3>{i.title}</h3><p>{i.copy}</p></div><span className="read-link">Read more <ArrowRight size={13} /></span></article>)}</div></section></main></Shell>; }
function Conferences() { return <Shell><main><PageIntro kicker="The conference calendar" title="Meetings with a point of view." copy="Find your next place to present, listen, challenge, and leave with better work." /><section className="section"><EventList onlyType="Conference" /></section></main></Shell>; }
function Webinars() { return <Shell><main><PageIntro kicker="Live online exchange" title="A focused room for the right questions." copy="Shorter, sharper sessions for researchers, practitioners, and peers across the world." /><section className="section"><EventList onlyType="Webinar" /></section></main></Shell>; }
function Contact() { const [sent, setSent] = useState(false); return <Shell><main><PageIntro kicker="Start a conversation" title="Get in touch with Stream Conferences." copy="Whether you are presenting research, exploring registration, or discussing a partnership, our team is here to help." /><section className="section contact-layout"><div><div className="section-kicker">Departments</div>{[['General & Delegate Inquiries', 'info@streamconferences.com'], ['Abstract Submissions & Speaker Desk', 'abstracts@streamconferences.com'], ['Publishing & Research Indexing', 'publishing@streamconferences.com'], ['Sponsorships & Strategic Partnerships', 'partners@streamconferences.com']].map(([title, email]) => <article className="contact-card" key={email}><h3>{title}</h3><a href={`mailto:${email}`}>{email}</a></article>)}</div><form className="contact-form" onSubmit={(e) => { e.preventDefault(); setSent(true); }}><div className="section-kicker">Send us a message</div>{sent ? <div className="success-state"><h2>Message received.</h2><p>Thank you. A member of the Stream team will respond within 24–48 business hours.</p></div> : <><input required placeholder="Full name" /><input required type="email" placeholder="Email address" /><select defaultValue=""><option value="" disabled>Inquiry type</option><option>General</option><option>Abstract submission</option><option>Publishing</option><option>Sponsorship</option></select><textarea required placeholder="How can we help?" rows={6} /><button className="cta-button" type="submit">Send message <Send size={14} /></button></>}</form></section></main></Shell>; }
function ContactBand() { return <section className="contact-band"><div className="contact-inner reveal"><div><div className="eyebrow">Have a question or a proposal?</div><h2>Bring the next good question.</h2></div><Link href="/contact" className="cta-button">Start a conversation <Send size={14} /></Link></div></section>; }
function Footer() { return <footer className="footer"><div className="footer-inner"><div><Link href="/" className="brand"><span className="brand-mark">S</span><span><span className="brand-word">StreamConferences</span><span className="brand-sub">An event by Stream Conferences</span></span></Link><p className="footer-note">Independent spaces for the people moving knowledge forward.</p></div><div><h3>Explore</h3>{nav.slice(1, 6).map(([l, h]) => <Link href={h} key={h}>{l}</Link>)}</div><div><h3>Connect</h3><a href="mailto:hello@streamconferences.org"><Mail size={13} /> hello@streamconferences.org</a><Link href="/contact">Partner with Stream</Link><Link href="/gallery">Press &amp; media</Link></div><div><h3>Trust</h3><Link href="/about">About Stream</Link><Link href="/contact">Code of conduct</Link><Link href="/contact">Accessibility</Link></div></div><div className="bottom-line"><span>© 2027 Stream Conferences</span><span>Global research exchange · Built for the work</span></div></footer>; }
function Router() { return <ErrorBoundary><Switch><Route path="/" component={Home} /><Route path="/about" component={About} /><Route path="/gallery" component={Gallery} /><Route path="/blog" component={Blog} /><Route path="/conferences" component={Conferences} /><Route path="/webinars" component={Webinars} /><Route path="/contact" component={Contact} /><Route component={NotFound} /></Switch></ErrorBoundary>; }
function App() { return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><Router /></WouterRouter><Toaster /></TooltipProvider></QueryClientProvider>; }
export default App;